# Use zsh as default shell
set-option -g default-shell /bin/zsh

# load plugin manager (Mac path; skip if missing)
if-shell "test -f /usr/local/opt/tpm/share/tpm/tpm" "run '/usr/local/opt/tpm/share/tpm/tpm'"
set -g @plugin 'tmux-plugins/tmux-logging'

# Use the xterm-256color terminal
set -g default-terminal "tmux-256color"
set -g xterm-keys on

# Apply Tc
set-option -ga terminal-overrides ",tmux-256color:Tc"

# Reload config
bind r source-file ~/.tmux.conf

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Start window and pane numbering from 1
set -g base-index 1
setw -g pane-base-index 1

# VIM mode
set-window-option -g mode-keys vi

# Navigation
bind -n 'M-Left' select-pane -L
bind -n 'M-Down' select-pane -D
bind -n 'M-Up' select-pane -U
bind -n 'M-Right' select-pane -R
bind -n 'C-Space' copy-mode
bind -n 'C-Left' select-window -n
bind -n 'C-Right' select-window -p

# Clipboard
set -g set-clipboard on
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Buffer
set-option -g history-limit 5000

# Default path
bind % split-window -h -c '#{pane_current_path}'
bind '"' split-window -v -c '#{pane_current_path}'

# Jump to command
bind -T copy-mode-vi . send-keys -X next-prompt
bind -T copy-mode-vi , send-keys -X previous-prompt
bind -T copy-mode-vi < send-keys -X search-forward " "
bind -T copy-mode-vi > send-keys -X search-backward " "

######################
### DESIGN CHANGES ###
######################

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action any

# modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# panes
set -g pane-border-style 'fg=colour2 bg=colour18'
set -g pane-active-border-style 'fg=colour9 bg=colour18'

# Dim inactive panes
set -g window-style 'fg=colour245,bg=colour236'
set -g window-active-style 'fg=terminal,bg=colour0'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=colour18 fg=colour137 dim'
set -g status-left '#[fg=colour255,bg=colour4] #{?CODER_WORKSPACE_NAME,#{CODER_WORKSPACE_NAME},#h} #[default] '
set -g status-right '#[fg=colour2,bg=colour19] %m/%d #[fg=colour233,bg=colour8] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 40

setw -g window-status-current-style 'fg=colour1 bg=colour19 bold'
setw -g window-status-current-format ' #I#[fg=colour249]:#[fg=colour255]#W#[fg=colour249]#F '

setw -g window-status-style 'fg=colour9 bg=colour18'
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'

# messages
set -g message-style 'fg=colour15 bg=colour16 bold'
